<script src="https://platform.twitter.com/widgets.js"></script>
<script src="/assets/site/js/isotope.pkgd.min.js"></script>
<script src="/assets/site/js/sticky_submenu.js"></script>
<script src="/assets/site/js/kidsfirst.js"></script>

<!-- Simple Pass only, just used to protect against peeking, not secured   	
<script>	
    if (localStorage.password != "oicr") { 	
        var password = prompt("Please enter the password to continue", "");	
        if (password != "oicr") {	
            $("a").click(function() { return false; });	
            $( "body" ).empty();	
        } else {	
            localStorage.setItem("password", password);	
        }	
    }	
</script>
-->

<script type="text/javascript">
(function() { var s = document.createElement("script"); s.type = "text/javascript"; s.async = true; s.src = '//api.usersnap.com/load/4f054d5e-acc5-4234-ba44-52b286a11c35.js';
var x = document.getElementsByTagName('script')[0]; x.parentNode.insertBefore(s, x); })();
</script>
