<!--[if lte IE 9]>
<div id="news-filter" clas="section">
    <div class="container">
        <div class="row filter-wrapper">
            <div class="col-lg-2 col-sm-4 col-xs-6 filter-item">
                <button class="btn-filter">
                    <span class="icon icon-alltopics"></span>
                    <span>All Topics</span>
                </button>
            </div>
            <div class="col-lg-2 col-sm-4 col-xs-6 filter-item">
                <button class="btn-filter">
                    <span class="icon icon-news"></span>
                    <span>News</span>
                </button>
            </div>
            <div class="col-lg-2 col-sm-4 col-xs-6 filter-item">
                <button class="btn-filter">
                    <span class="icon icon-press"></span>
                    <span>In the Press</span>
                </button>
            </div>
            <div class="col-lg-2 col-sm-4 col-xs-6 filter-item">
                <button class="btn-filter">
                    <span class="icon icon-studies"></span>
                    <span>Study Updates</span>
                </button>
            </div>
            <div class="col-lg-2 col-sm-4 col-xs-6 filter-item">
                <button class="btn-filter">
                    <span class="icon icon-events"></span>
                    <span>Events</span>
                </button>
            </div>
            <div class="col-lg-2 col-sm-4 col-xs-6 filter-item">
                <button class="btn-filter">
                    <span class="icon icon-spotlight"></span>
                    <span>In the Spotlight</span>
                </button>
            </div>
        </div>
    </div>
</div>
<![endif]-->
<!--[if gt IE 9]>
<div id="news-filter" clas="section">
    <div class="container">
        <div class="row filter-wrapper">
            <div class="col-lg-2 col-sm-4 col-xs-6 filter-item">
                <button class="btn-filter">
                    <span class="icon icon-alltopics"></span>
                    <span>All Topics</span>
                </button>
            </div>
            <div class="col-lg-2 col-sm-4 col-xs-6 filter-item">
                <button class="btn-filter">
                    <span class="icon icon-news"></span>
                    <span>News</span>
                </button>
            </div>
            <div class="col-lg-2 col-sm-4 col-xs-6 filter-item">
                <button class="btn-filter">
                    <span class="icon icon-press"></span>
                    <span>In the Press</span>
                </button>
            </div>
            <div class="col-lg-2 col-sm-4 col-xs-6 filter-item">
                <button class="btn-filter">
                    <span class="icon icon-studies"></span>
                    <span>Study Updates</span>
                </button>
            </div>
            <div class="col-lg-2 col-sm-4 col-xs-6 filter-item">
                <button class="btn-filter">
                    <span class="icon icon-events"></span>
                    <span>Events</span>
                </button>
            </div>
            <div class="col-lg-2 col-sm-4 col-xs-6 filter-item">
                <button class="btn-filter">
                    <span class="icon icon-spotlight"></span>
                    <span>In the Spotlight</span>
                </button>
            </div>
        </div>
    </div>
</div>
<![endif]-->